import React from 'react';
import ReactDOM from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import outputs from '../amplify_outputs.json';
import App from './App.jsx';
import './styles.css';

// amplify_outputs.json is generated by `npx ampx sandbox` (see amplify/)
// and is gitignored — it's environment-specific, not app source. A fresh
// clone needs to deploy its own sandbox before `npm run dev`/`npm run
// build` will work; `npm test` doesn't need it since no test imports this
// entry point.
Amplify.configure(outputs);

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <Authenticator>
      {({ signOut, user }) => <App signOut={signOut} user={user} />}
    </Authenticator>
  </React.StrictMode>
);
